apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Remote base from upstream - version is explicit here
# To upgrade: change version number in all three URLs below
resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v1.7.0/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.7.0/kubevirt-cr.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.64.0/cdi-operator.yaml
  - https://github.com/kubevirt/containerized-data-importer/releases/download/v1.64.0/cdi-cr.yaml
