apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grist-ingress
  namespace: grist
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: grist-home
      port:
        number: 8484
  tls:
    - hosts:
        - grist
