apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - kasm-ingress.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/source/helm/valuesObject/publicAddr
        value: https://kasm.tail9a43.ts.net
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: kasm-helm-chart
      namespace: kasm
