apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: gotenberg
  name: gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gotenberg
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: gotenberg
    spec:
      containers:
        # renovate: datasource=docker depName=docker.io/gotenberg/gotenberg
        - args:
            - gotenberg
            - --chromium-disable-javascript=true
            - --chromium-allow-list=file:///tmp/.*
          image: docker.io/gotenberg/gotenberg:8.22@sha256:91035c5041e7f986ae89d0e9f1783233dbae4254b19a33f954288466de5d150f
          name: gotenberg
      restartPolicy: Always
