apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: tika
  name: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tika
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: tika
    spec:
      containers:
        # renovate: datasource=docker depName=docker.io/apache/tika
        - image: docker.io/apache/tika:3.2.3.0
          name: tika
      restartPolicy: Always
