apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-app.yaml
  # - argocd-image-updater-app.yaml
  - sealed-secrets-app.yaml
  - metrics-server-app.yaml
  - kubelet-serving-certificate-approver-app.yaml
  - external-snapshotter-crd-app.yaml
  - external-snapshotter-controller-app.yaml
  - longhorn-app.yaml
  - longhorn-volume-snapshot-class.yaml
  - tailscale-operator-app.yaml
  - cnpg-app.yaml
  - velero-app.yaml
  - cert-manager-app.yaml
  - intel-device-plugins-operator-app.yaml
  - descheduler-app.yaml
  - newt-app.yaml
  - kubevirt-app.yaml
