apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: renovate
  annotations:
    tailscale.com/funnel: "true"
spec:
  defaultBackend:
    service:
      name: renovate-mend-renovate-ce
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - renovate

