---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: actual-budget-config
  namespace: actual-budget
spec:
  encryptedData:
    client_id: AgAkdDtWCLLHVGhOynj5KPXCiKW3UpiI0bj0cxGciEFIzx9icwxMpuauUrx5rygR5VwQtzxOkJPNVBghGN8EIzt3YsdYSWlqG97myuMv/YK8fByYfpkp90Rq77Z7ki+72B9pjAmaVzMikh9Kwwbqwzx2lniXRZf+0fUY7A87ggJ4KyGmLm2MVlJCTOJKlj2bxTuWbxH0XJWw3fpYaBMany606DIPxsagGXAK1rctXWEFQ+/x5Kw/4dZJEot3BA7K8DXMfZW48eXgpkRahb8BOjVVNFUA2pHDN4MTj3WU6O+MAmKLyY9e+HsRj5bc4gX5bJnd8y21j06IZsuvZdM7gTccK+qiixhRguQSOCLLHiug5lAdAaIKEO4m8No2aGt/Yygd5h7SmTF2EmgZoQdHa6JfWBcyVfFV5Mh7p7O2WRkibV6P0SqsxbfqWjCSYDhL5iwlrSHPV/nA9vbLKebw/jcl6/dlRiQeDT7O/LGhLqrBzc0X0QMqxt/fNjbPZR/bYZsjNVOAEe8XDJguShm3wk/uFqmu/8yt/9h8k2XUhNDsf4kgNF2mh4YAGhoNBmDAoWBPpR/2zMXSEepx7F4wpzx4Rdhz4oXoQie7WCYgiTGY23MT6HzbfkdpyrUBs/4o++zrPB+dHf9iyp/jY6oHsBDjgQa++DZdafqCc/vms4cJIQwmDuRCbuov8NO5QtYbpuo3Io1B0JEJ/Kw8zLU=
    client_secret: AgCXWfEybNZNEBCnwj4NNCaK7OY/3lXD7LaviCMjGBLjRzizSBkQdNueQ0lLltq4KxC9XoiUVGD66xPvDfZ0fo8/V9Wlgn3PxyxXODhuHp3QQSWNbgtBhZ+Fk/jBqC1YqwPf29aS4NNCoc6qHOAOboSXY87aEWbAors9GqV+L20buZia45HMUygN29o3CPLf7TTKs1P9wO42CjSK76nb1bDQcsJ9Xlor6dmRVVZH5TMUAp6e5H8q7/sSUB6oxZkL/sN/oXTXRFCFGXJV6DcQOrp0xjZ6flXQw2P+AsQ4P9vpZy+ibnz6RWZRRcgp6ugjniJK9QFRietLiPacjfAzLUj7QLe7vGaqKGKTQ19wGras69G2Dcdl5wHvlUNy6tmrPk31gPS3zp/JZIV9IxF31/9sQdEiJuvrVIR+8iOA36c88O5U6PNnBurwrPvqBSzsqnRZkUJn4a0qtZTNW6gLO/pN7zjDbipK/ddoA2jAHSnqf7mkQ1BxDanY9Of/IeYl/EmyKoBozKDNaTdLKzZ+8taEpzftgXqbaj3qnwcRMrtw3goxC3RJBHlDc0uRBdSAqRV0ASmfDa68burwcj6ksxdRzS1TNG8HR3EbRgIHuqZs4NsKb4RhYH1d+7+xqjkxSN0KXQxk1V1ZmMjWODKwJ6nJFdmKMxTleb17I+nshY4+IbJPz1AMJewOLHzsbAh9oSz8igVLcbLSCGHGv52JeAcXwYQtuZJepIuNc1j1ogqbpw==
  template:
    metadata:
      name: actual-budget-config
      namespace: actual-budget
